# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3119e47d45748da33d9fe4cc2e6ec3a40440227554614151ffea4595a78f9a29551510bd4147026fc9a23c65bb6a920e1657cba8a42966125c87e7de4ad42ae8

test:
  secret_key_base: 50a3a29a827311dacec6a45ac386110ff98f17174390d5e39d9df7a8f97972f404667cf5482e9d962a8dd3def1cdf0d711787801731cc9d31523b6cd04946c47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
